# Имя рабочего процесса, которое будет отображаться во вкладке "Actions"
name: Run Python Script Every 5 Minutes

# Блок, определяющий, когда запускать этот рабочий процесс
on:
  # Позволяет запускать этот процесс вручную со страницы "Actions"
  workflow_dispatch:

  # Запуск по расписанию
  schedule:
    # Запускать каждые 5 минут. Это минимально возможный интервал.
    # Формат CRON: минута час день(месяца) месяц день(недели)
    - cron: '*/5 * * * *'

# Задачи, которые будут выполняться
jobs:
  # Идентификатор задачи (может быть любым)
  build:
    # Указываем, что задача должна выполняться на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги, которые будут выполнены в рамках этой задачи
    steps:
      # Шаг 1: Клонирование вашего репозитория
      # Это необходимо, чтобы получить доступ к вашему Python-скрипту
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Настройка окружения Python
      # Устанавливает указанную версию Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Использует последнюю стабильную версию Python 3

      # Шаг 3: Запуск вашего скрипта
      # Убедитесь, что имя файла 'main.py' совпадает с именем вашего скрипта
      - name: Run Python script
        run: python main.py
