name: Update Log File Daily

on:
  # Запускаем вручную для теста
  workflow_dispatch:
  # Запускаем по расписанию (например, раз в день в полночь по UTC)
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    # !!! ВАЖНО: Даем разрешение на запись в репозиторий
    permissions:
      contents: write

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Шаг 3: Запускаем скрипт, который обновляет файл
      - name: Run script to update log
        run: python update_log.py

      # Шаг 4: Коммитим и отправляем изменения обратно в репозиторий
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add log.txt
          # Коммитим, только если есть реальные изменения в файле
          git diff --staged --quiet || git commit -m "Автоматическое обновление лога"
          git push
